version: "3.7"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway/src:/api-gateway/src ## 왼쪽(밖에 있는것)이 수정되면 오른쪽(안에 있는것)이 수정된다.

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth-service/src
  resource-service:
    build:
      context: ./services/resource
      dockerfile: Dockerfile
    volumes:
      - ./services/resource/src:/resource-service/src
