steps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker-real/backend/docker-compose.prod.yaml
      - build

    # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - docker-compose
      - -f
      - class/deploy-with-docker-real/backend/docker-compose.prod.yaml
      - push

    # 3단계 => kubectl set image deployment/mybackend-nestjs my-backend-sha256-1=asia.gcr.io/younghoogogo/my-backend:1.7
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/mybackend-nestjs
      - my-backend-sha256-1=asia.gcr.io/younghoogogo/my-backend:1.7

    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=mybackend-cluster-1
