export class ProductService {
    checkSoldout = () => { 
        console.log("판매가 완료되었는지 검증합니다.")
        
        // 이 기능만 요청하면 어디서든 판매여부 알 수 있다.
    // 1. 판매여부 검증하는 코드 (대략 10줄 정도)
    // ...
    // ...
    // ...
    // ...
    }
}