version: "3.3"

services:
    mini_backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/mini_backend/index.js
            - ./swagger/get.swagger.js:/mini_backend/./swagger/get.swagger.js
            - ./swagger/patch.swagger.js:/mini_backend/./swagger/patch.swagger.js
            - ./swagger/post.swagger.js:/mini_backend/./swagger/post.swagger.js
        ports:
            - 3000:3000

    mini_database:
        image: mongo:5
        ports:
            - 27017:27017