version: "3.3"

services: 
    my_backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - ./index.js:/my_backend/index.js
          - ./email.js:/my_backend/email.js    
        ports:
            - 3000:3000
    
    my_database:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports: 
            - 27017:27017